name: chessever2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #for localization
  intl: ^0.20.2

  #for network query
  http: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  #for widget testing
  # device_preview_plus: ^2.4.2

  #for state management
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1

  #for icons library
  font_awesome_flutter: ^10.8.0
  #render svg icons
  flutter_svg: ^2.1.0

  #for custom dropdown button and country picker and flags
  country_flags: ^3.3.0
  dropdown_button2: ^2.3.9
  country_picker: ^2.0.25
  country_code: ^1.1.0
  skeletonizer: ^2.0.1

  #cached network image
  cached_network_image: ^3.4.1


  #supabase
  supabase_flutter: ^2.0.0

  #authentication
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  #for hashing
  crypto: ^3.0.6

  #secure key storage
  flutter_dotenv: ^5.1.0


  #for settings persistence
  shared_preferences: ^2.5.3

  #for class origin
  equatable: ^2.0.7

  #for late action for frequent calls
  easy_debounce: ^2.0.3

  #for launching url
  url_launcher: ^6.3.1
  advanced_chess_board:
    path : advanced_chess_board

  chess: ^0.8.1
  stockfish: ^1.7.1
  flutter_local_notifications: ^19.3.0

  permission_handler: ^12.0.0+1

  flutter_native_splash: ^2.4.6
  purchases_flutter: ^8.10.6
  logger: ^2.6.1
  collection: ^1.19.1

  chessground: ^7.1.6
  dartchess: ^0.11.1
  fast_immutable_collections: ^11.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true # Added for localization

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/Inter-Bold.otf
    - assets/fonts/Inter-Medium.otf
    - assets/fonts/Inter-Regular.otf
    - assets/svgs/
    - assets/pngs/
    - assets/launch.jpg
    - assets/app_icon.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

#setting up splash screen settings
flutter_native_splash:
  color: "#1a1a1c"
  image: assets/launch.jpg
  color_dark: "#1a1a1c"
  image_dark: assets/launch.jpg

  # Platform settings
  android: true
  ios: true
  web: false

  # Fullscreen settings
  fullscreen: true

  # Additional settings for better fullscreen experience
  android_gravity: fill
  ios_content_mode: aspectFill

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#1a1a1c"
    theme_color: "#1a1a1c"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"