#!/usr/bin/env python3
"""Generate the Puzzle Race sounds with the ElevenLabs Sound Generation API.

Writes ``assets/sfx/race_<name>.mp3``. ``assets/sfx/`` is already a registered
asset directory, so no pubspec change is needed. The app loads these on demand
when a race warms up (``AudioPlayerService.loadRaceAssets``), never at start.

The set is one family with the board's wooden piece sounds and the felt-mallet
/ glass classification sounds (``tool/generate_classification_sfx.py``, whose
finishing helpers this reuses): dry wood and felt for the clock, warm glass for
the rewards, a low wooden heartbeat for the pressure.

  countdown_beat   tight low tick, played for 3-2-1 (the "1" a touch higher)
  go               sharp start hit, clack plus glass ring
  correct          quick bright success blip
  correct_streak   the same blip layered a fifth and an octave up (streak >= 3)
  wrong            short dull buzz-thud, disappointed, never harsh
  level_up         short upward whoosh into a chime
  tension_loop     seamless 3.2 s heartbeat bed, looped under the race
  last_life        one heavier, lower heartbeat accent
  finish           resolving final hit
  new_best         short triumphant flourish

Two steps. The API generates SOURCE takes (``TAKES``); the shipped sounds
(``SHIPPED``) are built from the chosen takes, most from one take trimmed and
levelled, some layered from several:

* ``correct_streak`` is the ``correct`` take stacked a fifth and an octave up,
  so the streak sound is literally the brighter version of the plain one.
* The heartbeat is not the model's: its heartbeats are sub-bass only (nothing
  on a phone speaker) and it cannot hold a tempo. Each beat is the countdown
  tick pitched down and muffled into a lub-dub, over a short sub thump from
  the ``heartbeat`` take for headphones. ``last_life`` is that beat, lower and
  closer. So the race's pulse is made of the same wood as its countdown.
* ``tension_loop`` places four of those beats at an exact 75 bpm and sums them
  circularly (a tail that runs past the end wraps round to the start), which
  makes the seam sample-exact. The wrap sits just before a beat, where the
  previous tail has decayed. The encoded mp3 carries the LAME gapless header,
  which SoLoud's dr_mp3 honours, so the decoded loop is exactly its length.

Key handling: the key is read from ``ELEVENLABS_API_KEY`` or, with
``--key-file``, from a JSON/JSONC file containing an ``"ELEVENLABS_API_KEY"``
entry (the git-ignored ``opencode.jsonc``). It is never taken from argv, never
printed, and scrubbed from any error body before that is shown.

    # Generate every source take and build every sound.
    python3 tool/generate_race_sfx.py --key-file opencode.jsonc --force
    # Audition: three raw takes of two sources into build/race_sfx_takes.
    python3 tool/generate_race_sfx.py --key-file opencode.jsonc \\
        --only go,heartbeat --variants 3
    # Pick takes (repeatable); every sound using them is rebuilt.
    python3 tool/generate_race_sfx.py \\
        --choose go build/race_sfx_takes/race_go_v2.mp3
    # Rebuild everything from the chosen takes, no API calls.
    python3 tool/generate_race_sfx.py --build

Chosen takes live in ``build/race_sfx_takes/chosen`` (git-ignored). Every
finished file peaks at or below -3 dBFS (needs ffmpeg).
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from collections import deque
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_classification_sfx import (  # noqa: E402  (after the path fix)
    SAMPLE_RATE,
    Note,
    _db,
    _decode,
    _encode,
    _level,
    _read_key,
    _render,
    _smoothstep,
)

API_URL = "https://api.elevenlabs.io/v1/sound-generation"
MODEL_ID = "eleven_text_to_sound_v2"
OUTPUT_FORMAT = "mp3_44100_128"
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "assets" / "sfx"
RAW_DIR = REPO_ROOT / "build" / "race_sfx_takes"
CHOSEN_DIR = RAW_DIR / "chosen"

# Shared tail: the same material as the board (wood) and the classification
# set (felt mallets, warm glass), pushed a little towards pressure, and away
# from the arcade / game-show register the model drifts into by default. The
# API caps the whole text at 450 characters.
_STYLE = (
    "Premium minimal sound for a timed chess puzzle race, warm wooden and "
    "felt mallet percussion with soft glass bell tones, dry close studio "
    "recording, clean, no voice, no music bed, not cartoonish, not arcade, "
    "starts instantly"
)
_MAX_TEXT = 450

_SILENCE_DB = -50.0  # below the take's own peak
_PRE_ROLL_S = 0.004


@dataclass(frozen=True)
class Take:
    """A source generated by the API."""

    prompt: str
    duration: float  # asked of the API (0.5 s and up)
    influence: float


@dataclass(frozen=True)
class Layer:
    """One voice of a shipped sound, cut from a source take."""

    source: str
    start: float = 0.0  # seconds into the sound
    ratio: float = 1.0  # pitch ratio, tape style (1.5 = a fifth up)
    gain: float = 1.0
    # Fade the voice out between these times (seconds from its start).
    release: tuple[float, float] | None = None
    # Start this many ms before the source's loudest transient instead of at
    # its first audible sample (cuts a slow swell down to a short lead-in).
    align_to_peak_ms: float | None = None
    lowpass_hz: float | None = None  # muffles the voice (4-pole)
    highpass_hz: float | None = None  # drops rumble that eats headroom
    seconds: float | None = None  # use only this much of the source
    # Soft saturation (tanh) before the filters: grows harmonics above a low
    # fundamental, so a thud a phone speaker cannot reproduce is still heard
    # (the missing-fundamental trick). 1 = clean.
    drive: float = 1.0


@dataclass(frozen=True)
class LoopSpec:
    """Places the built sound as the beats of a seamless loop."""

    period: float  # seconds between beats
    beats: tuple[tuple[float, float], ...]  # (gain, pitch ratio) per beat
    offset: float  # first beat's start; the seam sits just before it


@dataclass(frozen=True)
class Shipped:
    """A file in ``assets/sfx``: layers mixed, capped, faded and levelled."""

    layers: tuple[Layer, ...]
    max_seconds: float  # hard cap (for a loop: one beat's length)
    rms_db: float  # target RMS; the -3 dBFS peak ceiling wins when lower
    highpass_hz: float | None = None  # on the whole mix
    # Pull the loudest transient down this far before levelling, so a sharp
    # click does not hold the body of the sound under the peak ceiling.
    limit_db: float = 0.0
    tail_fade: float = 0.06  # seconds of smooth fade before the cap
    loop: LoopSpec | None = None

    @property
    def sources(self) -> set[str]:
        return {layer.source for layer in self.layers}


TAKES: dict[str, Take] = {
    "countdown_beat": Take(
        "One single tight low wooden tick, a muted woodblock struck together "
        "with a soft low felt drum, short dry and precise, like a clock "
        "counting down, tense and focused",
        0.5,
        0.7,
    ),
    "go": Take(
        "One sharp bright start hit: a tiny quick upward swipe snapping "
        "into a punchy wooden clack and bright glass bell with a short ring, "
        "decisive, not a long sweep",
        0.8,
        0.65,
    ),
    "correct": Take(
        "A quick bright success blip, one short clean glass bell tap with a "
        "soft wooden click at the front, light, positive and very short",
        0.5,
        0.7,
    ),
    "wrong": Take(
        "A short dull thud with a brief low muted buzz, a felt mallet on a "
        "damped low wooden drum, disappointed but gentle, not harsh, no "
        "alarm, no beep",
        0.5,
        0.65,
    ),
    "level_up": Take(
        "A short airy upward whoosh rising in pitch that resolves into one "
        "clear bright glass bell chime, a step up, uplifting and quick",
        1.0,
        0.65,
    ),
    # Only the sub thump under the wooden heartbeat is used.
    "heartbeat": Take(
        "One close-miked heartbeat: two soft punchy thumps, lub then dub, "
        "each with a clear attack, like a soft felt beater on a low floor "
        "tom, warm low-mid body that is audible on small speakers, tense, "
        "then silence",
        0.8,
        0.7,
    ),
    "finish": Take(
        "A resolving final hit: a warm vibraphone-like felt mallet bell "
        "chord, major and settled, struck together with one soft low wooden "
        "drum hit underneath, conclusive and satisfying, the end of a race, "
        "gentle ringing decay",
        1.4,
        0.65,
    ),
    "new_best": Take(
        "A short triumphant flourish: a quick rising run of bright glass "
        "bell notes landing on a warm major chord with a soft shimmer, "
        "celebratory but classy and understated",
        1.5,
        0.65,
    ),
}


def _lub_dub(depth: float, weight: float) -> tuple[Layer, ...]:
    """One heartbeat: the countdown tick pitched down by [depth] and muffled,
    lub then a softer dub 0.2 s later, each over a short sub thump."""
    tick = {"lowpass_hz": 1600.0, "align_to_peak_ms": 3.0, "seconds": 0.3}
    # The thump is only weight under the tick: its beater click is filtered
    # out so the loop never clicks on every beat.
    thump = {"highpass_hz": 35.0, "lowpass_hz": 500.0}
    return (
        Layer("countdown_beat", 0.0, 0.75 * depth, 1.0, **tick),
        Layer("heartbeat", 0.0, 1.0 * depth, 0.8 * weight,
              release=(0.14, 0.32), **thump),
        Layer("countdown_beat", 0.2, 0.84 * depth, 0.55, **tick),
        Layer("heartbeat", 0.2, 1.1 * depth, 0.4 * weight,
              release=(0.10, 0.28), **thump),
    )


SHIPPED: dict[str, Shipped] = {
    # Played three times, a second apart, before the clock starts.
    "countdown_beat": Shipped(
        (Layer("countdown_beat", align_to_peak_ms=6),),
        0.24,
        -22.0,
        highpass_hz=60.0,
    ),
    # The clock starts. The pitch climb from the low ticks to this bright
    # hit is the "rise"; the take's own short swipe leads into it.
    "go": Shipped(
        (Layer("go", align_to_peak_ms=90),),
        0.82,
        -19.5,
        limit_db=5.0,
        tail_fade=0.32,
    ),
    # The most frequent reward, so short, light and not loud.
    "correct": Shipped(
        (Layer("correct", align_to_peak_ms=4),),
        0.3,
        -23.0,
        limit_db=2.0,
        tail_fade=0.12,
    ),
    # The plain blip, then the same take a fifth up a hair later with a soft
    # octave on top: brighter and layered, unmistakably the same family.
    "correct_streak": Shipped(
        (
            Layer("correct", 0.0, 1.0, 0.8, release=(0.05, 0.16),
                  align_to_peak_ms=4),
            Layer("correct", 0.055, 1.5, 1.0, align_to_peak_ms=4),
            Layer("correct", 0.058, 2.0, 0.32, align_to_peak_ms=4),
        ),
        0.4,
        -22.0,
        limit_db=2.0,
        tail_fade=0.14,
    ),
    # A miss costs a life. Nudged up two semitones, saturated and cut below
    # 120 Hz so the thud's buzz lands on a phone speaker; the low-pass keeps
    # it dull, never harsh.
    "wrong": Shipped(
        (Layer("wrong", 0.0, 1.12, align_to_peak_ms=4, drive=6.0,
               lowpass_hz=2200.0),),
        0.4,
        -20.5,
        highpass_hz=120.0,
        tail_fade=0.14,
    ),
    # Difficulty climbed: a short whoosh that resolves into one chime.
    "level_up": Shipped(
        (Layer("level_up"),),
        0.95,
        -21.0,
        tail_fade=0.2,
    ),
    # 75 bpm, four beats (3.2 s). Beats vary a touch in weight and pitch so
    # the bed breathes instead of ticking like a machine. The app raises the
    # play speed with tension (to ~84 bpm) and fades its volume.
    "tension_loop": Shipped(
        _lub_dub(1.0, 1.0),
        0.62,
        -24.0,
        limit_db=3.0,
        tail_fade=0.12,
        loop=LoopSpec(
            period=0.8,
            beats=((1.0, 1.0), (0.84, 0.992), (0.95, 1.0), (0.8, 0.988)),
            offset=0.02,
        ),
    ),
    # The loop's heartbeat two semitones lower, louder and closer.
    "last_life": Shipped(
        _lub_dub(0.89, 1.25),
        0.7,
        -19.0,
        limit_db=4.0,
        tail_fade=0.18,
    ),
    # The race is over: the bell chord carries it, so the drum's sub rumble
    # is kept out of the level.
    "finish": Shipped(
        (Layer("finish", align_to_peak_ms=6),),
        1.35,
        -20.0,
        highpass_hz=70.0,
        tail_fade=0.3,
    ),
    # A personal best, layered after the finish hit.
    "new_best": Shipped(
        (Layer("new_best"),),
        1.5,
        -19.5,
        limit_db=2.0,
        tail_fade=0.3,
    ),
}


def _dependents(sources: set[str]) -> list[str]:
    return [name for name, s in SHIPPED.items() if s.sources & sources]


# ---------------------------------------------------------------------------
# ElevenLabs.


def _generate(key: str, name: str, take: Take) -> bytes:
    text = f"{take.prompt}. {_STYLE}."
    if len(text) > _MAX_TEXT:
        raise ValueError(f"{name}: prompt is {len(text)} > {_MAX_TEXT} chars")
    body = json.dumps({
        "text": text,
        "duration_seconds": take.duration,
        "prompt_influence": take.influence,
        "model_id": MODEL_ID,
    }).encode("utf-8")
    request = urllib.request.Request(
        f"{API_URL}?output_format={OUTPUT_FORMAT}",
        data=body,
        method="POST",
        headers={
            "xi-api-key": key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        data = response.read()
        content_type = response.headers.get("Content-Type", "")
    if "audio" not in content_type and not data.startswith((b"ID3", b"\xff")):
        raise ValueError(
            f"{name}: expected audio, got {content_type or 'no content type'}"
        )
    if len(data) < 1024:
        raise ValueError(f"{name}: suspiciously small response ({len(data)} B)")
    return data


# ---------------------------------------------------------------------------
# Finishing (mono float lists at 44.1 kHz, plain Python).


def _trim(
    samples: list[float],
    *,
    max_seconds: float | None = None,
    align_to_peak_ms: float | None = None,
) -> list[float]:
    """Drops lead-in and tail silence (relative to the take's own peak: the
    API's masters differ by ~25 dB), optionally starting a few ms before the
    loudest transient."""
    peak_level = max((abs(s) for s in samples), default=0.0)
    floor = peak_level * 10 ** (_SILENCE_DB / 20)
    audible = [i for i, s in enumerate(samples) if abs(s) > floor]
    if not audible:
        return samples
    start = max(0, audible[0] - round(_PRE_ROLL_S * SAMPLE_RATE))
    if align_to_peak_ms is not None:
        peak = max(range(len(samples)), key=lambda i: abs(samples[i]))
        lead = round(align_to_peak_ms / 1000 * SAMPLE_RATE)
        start = max(start, peak - lead)
    end = audible[-1] + 1
    if max_seconds is not None:
        end = min(end, start + round(max_seconds * SAMPLE_RATE))
    return samples[start:end]


def _biquad(samples: list[float], hz: float, *, high: bool) -> list[float]:
    """RBJ cookbook 2-pole Butterworth low/high-pass."""
    w0 = 2 * math.pi * hz / SAMPLE_RATE
    alpha = math.sin(w0) / (2 * math.sqrt(0.5))
    cos_w0 = math.cos(w0)
    if high:
        b0, b1, b2 = (1 + cos_w0) / 2, -(1 + cos_w0), (1 + cos_w0) / 2
    else:
        b0, b1, b2 = (1 - cos_w0) / 2, 1 - cos_w0, (1 - cos_w0) / 2
    a0, a1, a2 = 1 + alpha, -2 * cos_w0, 1 - alpha
    b0, b1, b2, a1, a2 = b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0
    out: list[float] = []
    x1 = x2 = y1 = y2 = 0.0
    for x in samples:
        y = b0 * x + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        out.append(y)
        x2, x1, y2, y1 = x1, x, y1, y
    return out


def _filtered(
    samples: list[float], low: float | None, high: float | None
) -> list[float]:
    if high is not None:
        samples = _biquad(samples, high, high=True)
    if low is not None:  # two stages: a steep, click-free muffle
        samples = _biquad(_biquad(samples, low, high=False), low, high=False)
    return samples


def _fade(samples: list[float], tail: float) -> list[float]:
    """2 ms fade-in (a peak-aligned start can land mid-waveform) and a
    smooth [tail]-second fade-out, so a cap never ends on a cliff."""
    out = list(samples)
    fade_in = min(len(out), round(0.002 * SAMPLE_RATE))
    for i in range(fade_in):
        out[i] *= i / fade_in
    fade_out = min(len(out) // 2, round(tail * SAMPLE_RATE))
    for i in range(fade_out):
        out[len(out) - fade_out + i] *= 1 - _smoothstep(i / fade_out)
    return out


def _saturate(samples: list[float], drive: float) -> list[float]:
    """tanh soft clip, driven relative to the take's own peak and scaled back
    so the peak stays where it was."""
    peak = max(abs(s) for s in samples) or 1.0
    norm = math.tanh(drive)
    return [math.tanh(drive * s / peak) / norm * peak for s in samples]


def _limit(samples: list[float], reduce_db: float) -> list[float]:
    """Lookahead peak limiter: the loudest peak comes down by [reduce_db].
    Gain ramps down over 1.5 ms ahead of each peak (so no step lands on a
    transient) and recovers over 60 ms."""
    if reduce_db <= 0:
        return samples
    peak = max(abs(s) for s in samples)
    ceiling = peak * 10 ** (-reduce_db / 20)
    need = [min(1.0, ceiling / abs(s)) if abs(s) > ceiling else 1.0
            for s in samples]
    ahead = max(1, round(0.0015 * SAMPLE_RATE))
    n = len(samples)
    # Sliding minimum of the needed gain over the next 2 * ahead samples.
    window = 2 * ahead
    lowest = [1.0] * n
    queue: deque[int] = deque()
    for j in range(n + window):
        if j < n:
            while queue and need[queue[-1]] >= need[j]:
                queue.pop()
            queue.append(j)
        i = j - window
        if i >= 0:
            while queue and queue[0] < i:
                queue.popleft()
            lowest[i] = need[queue[0]]
    # Moving average over [i - ahead, i]: a ramp that still never exceeds the
    # gain a peak needs (every value averaged at the peak is at most it).
    gains = [1.0] * n
    running = 0.0
    for i in range(n):
        running += lowest[i]
        if i > ahead:
            running -= lowest[i - ahead - 1]
        gains[i] = running / min(i + 1, ahead + 1)
    release = 1 - math.exp(-1 / (0.06 * SAMPLE_RATE))
    out: list[float] = []
    gain = 1.0
    for i, sample in enumerate(samples):
        gain = min(gains[i], gain + (1 - gain) * release)
        out.append(sample * gain)
    return out


def _stats(samples: list[float]) -> str:
    rms = math.sqrt(sum(s * s for s in samples) / max(len(samples), 1))
    peak = max(abs(s) for s in samples)
    return (
        f"{len(samples) / SAMPLE_RATE:.3f}s, rms {_db(rms):.1f} dB, "
        f"peak {_db(peak):.1f} dB"
    )


def _mix(
    layers: tuple[Layer, ...], sources: dict[str, list[float]]
) -> list[float]:
    voices: list[tuple[int, list[float]]] = []
    for layer in layers:
        source = _trim(
            sources[layer.source],
            max_seconds=layer.seconds,
            align_to_peak_ms=layer.align_to_peak_ms,
        )
        if layer.seconds is not None:
            source = _fade(source, min(0.08, layer.seconds / 3))
        if layer.drive != 1.0:
            source = _saturate(source, layer.drive)
        source = _filtered(source, layer.lowpass_hz, layer.highpass_hz)
        note = Note(0.0, layer.ratio, gain=layer.gain, release=layer.release)
        voices.append((round(layer.start * SAMPLE_RATE), _render(source, note)))
    length = max(offset + len(voice) for offset, voice in voices)
    mix = [0.0] * length
    for offset, voice in voices:
        for i, sample in enumerate(voice):
            mix[offset + i] += sample
    return mix


def _loop(beat: list[float], spec: LoopSpec) -> list[float]:
    """Circular sum of the beats: sample-exact seam, exact tempo."""
    length = round(spec.period * len(spec.beats) * SAMPLE_RATE)
    mix = [0.0] * length
    for index, (gain, ratio) in enumerate(spec.beats):
        voice = _render(beat, Note(0.0, ratio, gain=gain))
        start = round((spec.offset + index * spec.period) * SAMPLE_RATE)
        for i, sample in enumerate(voice):
            mix[(start + i) % length] += sample
    return mix


def _seam_jump(samples: list[float]) -> float:
    """The step across the wrap relative to the loop's typical step (1 is as
    smooth as anywhere else in the loop)."""
    steps = [abs(samples[i + 1] - samples[i]) for i in range(len(samples) - 1)]
    typical = sum(steps) / len(steps)
    return abs(samples[0] - samples[-1]) / max(typical, 1e-9)


def _decoded_frames(path: Path) -> int:
    """Frames ffmpeg decodes; it honours the LAME gapless header as SoLoud's
    dr_mp3 does."""
    result = subprocess.run(
        [
            "ffmpeg", "-hide_banner", "-nostats", "-i", str(path),
            "-f", "s16le", "-ac", "1", "-",
        ],
        capture_output=True,
        check=True,
    )
    return len(result.stdout) // 2


def build(name: str, tmp: Path) -> str:
    """Builds ``assets/sfx/race_<name>.mp3`` from the chosen takes."""
    spec = SHIPPED[name]
    sources = {
        source: _decode(CHOSEN_DIR / f"race_{source}.mp3", tmp)
        for source in spec.sources
    }
    samples = _mix(spec.layers, sources)
    if spec.highpass_hz is not None:
        samples = _filtered(samples, None, spec.highpass_hz)
    samples = _trim(samples, max_seconds=spec.max_seconds)
    samples = _fade(_limit(samples, spec.limit_db), spec.tail_fade)
    target = OUT_DIR / f"race_{name}.mp3"
    if spec.loop is None:
        samples = _level(samples, spec.rms_db)
        _encode(samples, target, tmp)
        return f"ok    race_{name}.mp3 {_stats(samples)}"
    samples = _level(_loop(samples, spec.loop), spec.rms_db)
    _encode(samples, target, tmp)
    decoded = _decoded_frames(target)
    gapless = (
        "gapless"
        if decoded == len(samples)
        else f"NOT GAPLESS: decodes {decoded} of {len(samples)} frames"
    )
    return (
        f"ok    race_{name}.mp3 {_stats(samples)}, seam "
        f"{_seam_jump(samples):.2f}x typical step, {gapless}"
    )


def build_all(names: list[str]) -> int:
    if shutil.which("ffmpeg") is None:
        print("ffmpeg is required to build the race sounds", file=sys.stderr)
        return 2
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    failures = 0
    with tempfile.TemporaryDirectory() as tmp_dir:
        for name in names:
            missing = [
                s for s in sorted(SHIPPED[name].sources)
                if not (CHOSEN_DIR / f"race_{s}.mp3").exists()
            ]
            if missing:
                failures += 1
                print(f"skip  race_{name}.mp3 (no chosen take: {missing})")
                continue
            print(build(name, Path(tmp_dir)))
    return 1 if failures else 0


def _choose(source: str, take: Path) -> None:
    CHOSEN_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(take, CHOSEN_DIR / f"race_{source}.mp3")


# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--only",
        help="comma-separated source takes to generate (default: all)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="regenerate sources that already have a chosen take",
    )
    parser.add_argument(
        "--key-file",
        help="JSON/JSONC file holding an ELEVENLABS_API_KEY entry",
    )
    parser.add_argument(
        "--variants",
        type=int,
        default=1,
        help="takes per source; >1 writes raw takes to --raw-dir to audition",
    )
    parser.add_argument(
        "--raw-dir",
        default=str(RAW_DIR),
        help="where raw takes go when --variants > 1",
    )
    parser.add_argument(
        "--choose",
        nargs=2,
        action="append",
        metavar=("SOURCE", "TAKE"),
        help="use TAKE for SOURCE and rebuild what uses it (repeatable)",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="rebuild every sound from the chosen takes (no API calls)",
    )
    args = parser.parse_args()

    if args.choose:
        chosen: set[str] = set()
        for source, take in args.choose:
            source = source.strip().removeprefix("race_")
            if source not in TAKES:
                print(f"unknown source: {source}", file=sys.stderr)
                return 2
            _choose(source, Path(take))
            chosen.add(source)
        return build_all(_dependents(chosen))

    if args.build:
        return build_all(list(SHIPPED))

    key = _read_key(args.key_file)
    if not key:
        print(
            "No ElevenLabs key: set ELEVENLABS_API_KEY or pass --key-file",
            file=sys.stderr,
        )
        return 2

    names = list(TAKES)
    if args.only:
        names = [n.strip().removeprefix("race_") for n in args.only.split(",")]
        unknown = [n for n in names if n not in TAKES]
        if unknown:
            print(f"unknown source(s): {', '.join(unknown)}", file=sys.stderr)
            return 2

    raw_dir = Path(args.raw_dir)
    if args.variants > 1:
        raw_dir.mkdir(parents=True, exist_ok=True)

    failures = 0
    generated: set[str] = set()
    for name in names:
        if (
            args.variants == 1
            and not args.force
            and (CHOSEN_DIR / f"race_{name}.mp3").exists()
        ):
            print(f"skip  {name} (chosen take exists; --force to regenerate)")
            continue
        for take_index in range(1, args.variants + 1):
            label = f"race_{name}" + (
                f"_v{take_index}" if args.variants > 1 else ""
            )
            try:
                data = _generate(key, name, TAKES[name])
            except urllib.error.HTTPError as error:
                failures += 1
                detail = error.read()[:200].decode("utf-8", "replace")
                detail = detail.replace(key, "***")  # never echo the key back
                print(f"FAIL  {label} HTTP {error.code}: {detail}")
                continue
            except (urllib.error.URLError, ValueError, TimeoutError) as error:
                failures += 1
                message = str(error).replace(key, "***")
                print(f"FAIL  {label} {type(error).__name__}: {message}")
                continue
            if args.variants > 1:
                path = raw_dir / f"{label}.mp3"
                path.write_bytes(data)
                print(f"take  {path} {len(data)} B")
            else:
                CHOSEN_DIR.mkdir(parents=True, exist_ok=True)
                (CHOSEN_DIR / f"race_{name}.mp3").write_bytes(data)
                generated.add(name)
            time.sleep(0.4)  # stay well under the per-second request limit

    if generated:
        failures += build_all(_dependents(generated))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
