-- Migration: Create library tables for saved analyses and folders (REVISED)
-- Purpose: Allow users to save and organize chess game analyses with COMPLETE state recovery
-- Created: 2025-01-21
-- Revised: 2025-01-21 - Added comprehensive comments and analysis_state structure

-- ============ FOLDER TABLES ============

-- Create user_folders table
CREATE TABLE IF NOT EXISTS public.user_folders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#0FB4E5',
  icon TEXT DEFAULT 'folder',
  order_index INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, name)
);

-- ============ SAVED ANALYSIS TABLES ============

-- Create user_saved_analyses table
-- This table stores COMPLETE chess analysis state for recovery
CREATE TABLE IF NOT EXISTS public.user_saved_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  folder_id UUID REFERENCES public.user_folders(id) ON DELETE SET NULL,
  title TEXT NOT NULL,

  -- Original game reference (if from live game)
  source_game_id TEXT,
  source_tournament_id TEXT,

  -- CORE GAME DATA (stored as JSONB for flexibility)
  -- This contains ChessGame.toJson() which includes:
  --   - gameId, startingFen, metadata
  --   - mainline: List<ChessMove> with recursive variations
  --   - Each ChessMove has: num, fen, san, uci, turn, clockTime, variations
  --   - variations: List<ChessLine> where ChessLine = List<ChessMove> (nested structure)
  -- This JSONB field captures the ENTIRE variation tree
  chess_game JSONB NOT NULL,

  -- ANALYSIS-SPECIFIC DATA
  -- analysis_state stores additional navigation/UI state as JSONB:
  -- {
  --   "move_pointer": [0, 1, 2],  // ChessMovePointer - exact navigation position in variation tree
  --   "is_board_flipped": false,  // Optional: board orientation preference
  --   "pv_base_fen": "rnbqkbnr...", // Optional: FEN where principal variations were generated
  --   "selected_variant_index": 0  // Optional: which engine suggestion was selected
  -- }
  analysis_state JSONB DEFAULT '{}'::jsonb,

  -- VARIATION COMMENTS
  -- Map<String, String> where keys are encoded ChessMovePointers
  -- Example: {"0": "Good opening", "0-1-2": "Interesting sacrifice in second variation"}
  -- Keys are generated by NotationPointer.encode(ChessMovePointer)
  variation_comments JSONB DEFAULT '{}'::jsonb,

  -- NAVIGATION STATE
  -- The move index where user was viewing (or -1 for starting position)
  last_viewed_position INT DEFAULT -1,

  -- METADATA
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  notes TEXT,
  is_favorite BOOLEAN DEFAULT false,

  -- TIMESTAMPS
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_opened_at TIMESTAMPTZ
);

-- ============ ROW LEVEL SECURITY ============

-- Enable RLS
ALTER TABLE public.user_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_saved_analyses ENABLE ROW LEVEL SECURITY;

-- Create policies for user_folders
CREATE POLICY "Users can view their own folders"
  ON public.user_folders
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own folders"
  ON public.user_folders
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own folders"
  ON public.user_folders
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own folders"
  ON public.user_folders
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create policies for user_saved_analyses
CREATE POLICY "Users can view their own saved analyses"
  ON public.user_saved_analyses
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saved analyses"
  ON public.user_saved_analyses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own saved analyses"
  ON public.user_saved_analyses
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saved analyses"
  ON public.user_saved_analyses
  FOR DELETE
  USING (auth.uid() = user_id);

-- ============ PERFORMANCE INDEXES ============

CREATE INDEX IF NOT EXISTS idx_user_folders_user_id ON public.user_folders(user_id);
CREATE INDEX IF NOT EXISTS idx_user_folders_order ON public.user_folders(user_id, order_index);

CREATE INDEX IF NOT EXISTS idx_user_saved_analyses_user_id ON public.user_saved_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_analyses_folder_id ON public.user_saved_analyses(folder_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_analyses_created_at ON public.user_saved_analyses(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_saved_analyses_favorite ON public.user_saved_analyses(user_id, is_favorite) WHERE is_favorite = true;

-- ============ AUTOMATIC TIMESTAMPS ============

-- Create triggers for updated_at (reuse existing function)
DROP TRIGGER IF EXISTS update_user_folders_updated_at ON public.user_folders;
CREATE TRIGGER update_user_folders_updated_at
  BEFORE UPDATE ON public.user_folders
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_saved_analyses_updated_at ON public.user_saved_analyses;
CREATE TRIGGER update_user_saved_analyses_updated_at
  BEFORE UPDATE ON public.user_saved_analyses
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();
